import { useState } from 'react';
import CredentialRevealer from './CredentialRevealer.jsx';
import './CredentialHistory.css';

/**
 * CredentialHistoryCard Component
 * 
 * Individual history entry card displaying credential version details.
 * 
 * Features:
 * - Color-coded reason badge
 * - Masked password with reveal toggle
 * - System and template information
 * - Selection for comparison
 * - Timestamp display
 * 
 * @param {Object} props
 * @param {Object} props.entry - History entry data
 * @param {boolean} props.isSelected - Whether this entry is selected
 * @param {Function} props.onSelect - Callback when selection toggled
 * @param {boolean} props.canSelect - Whether this entry can be selected
 */
function CredentialHistoryCard({ entry, isSelected, onSelect, canSelect }) {
  const [showDetails, setShowDetails] = useState(false);

  const getReasonColor = (reason) => {
    switch (reason?.toLowerCase()) {
      case 'initial':
        return 'reason-initial';
      case 'regeneration':
        return 'reason-regeneration';
      case 'manual':
        return 'reason-manual';
      case 'rotation':
        return 'reason-rotation';
      default:
        return 'reason-default';
    }
  };

  const getReasonLabel = (reason) => {
    switch (reason?.toLowerCase()) {
      case 'initial':
        return 'Initial';
      case 'regeneration':
        return 'Regeneration';
      case 'manual':
        return 'Manual';
      case 'rotation':
        return 'Rotation';
      default:
        return reason || 'Unknown';
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    const date = new Date(dateString);
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const formatSystemName = (name) => {
    if (!name) return 'Unknown';
    return name
      .replace(/-/g, ' ')
      .replace(/_/g, ' ')
      .replace(/\b\w/g, l => l.toUpperCase());
  };

  return (
    <div className={`history-card ${isSelected ? 'selected' : ''}`}>
      <div className="history-card-header">
        <div className="history-card-main">
          <label className="selection-checkbox">
            <input
              type="checkbox"
              checked={isSelected}
              onChange={onSelect}
              disabled={!canSelect && !isSelected}
              aria-label={`Select version ${entry.id} for comparison`}
            />
            <span className="checkbox-custom"></span>
          </label>

          <div className="system-info">
            <h4 className="system-name">{formatSystemName(entry.system)}</h4>
            <span className="version-id">Version {entry.id}</span>
          </div>

          <span className={`reason-badge ${getReasonColor(entry.reason)}`}>
            {getReasonLabel(entry.reason)}
          </span>
        </div>

        <div className="history-card-meta">
          <span className="timestamp">{formatDate(entry.createdAt)}</span>
          <button
            className="btn-toggle-details"
            onClick={() => setShowDetails(!showDetails)}
            aria-expanded={showDetails}
          >
            {showDetails ? 'Hide Details' : 'Show Details'}
            <span className={`toggle-icon ${showDetails ? 'expanded' : ''}`}>▼</span>
          </button>
        </div>
      </div>

      {showDetails && (
        <div className="history-card-details">
          <div className="credential-details">
            <div className="detail-field">
              <label>Username</label>
              <div className="detail-value">
                <code>{entry.username}</code>
              </div>
            </div>

            <div className="detail-field">
              <label>Password</label>
              <CredentialRevealer versionId={entry.id} />
            </div>

            <div className="detail-row">
              <div className="detail-field half">
                <label>Template Version</label>
                <div className="detail-value">
                  <span className="template-badge">v{entry.templateVersion}</span>
                </div>
              </div>

              <div className="detail-field half">
                <label>Generated By</label>
                <div className="detail-value">
                  <span className="user-badge">{entry.generatedBy || 'System'}</span>
                </div>
              </div>
            </div>

            {entry.notes && (
              <div className="detail-field">
                <label>Notes</label>
                <div className="detail-value notes">
                  {entry.notes}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export default CredentialHistoryCard;
