import { useState } from 'react';
import CredentialRevealer from './CredentialRevealer.jsx';
import { formatDisplayDateTime } from '../../../shared/utils/date-format.js';
import './CredentialHistory.css';

const IMAP_FIELD_LABELS = {
  email: 'Email address',
  firstName: 'First name',
  lastName: 'Last name',
  fullName: 'Full name',
  dob: 'Date of birth',
  phone: 'Phone number'
};

/**
 * CredentialHistoryCard Component
 * 
 * Individual history entry card displaying credential version details.
 * 
 * Features:
 * - Color-coded reason badge
 * - Masked password with reveal toggle
 * - System and template information
 * - Selection for comparison
 * - Timestamp display
 * 
 * @param {Object} props
 * @param {Object} props.entry - History entry data
 * @param {boolean} props.isSelected - Whether this entry is selected
 * @param {Function} props.onSelect - Callback when selection toggled
 * @param {boolean} props.canSelect - Whether this entry can be selected
 */
function CredentialHistoryCard({ entry, isSelected, onSelect, canSelect }) {
  const [showDetails, setShowDetails] = useState(false);

  const getReasonColor = (reason) => {
    switch (reason?.toLowerCase()) {
      case 'initial':
        return 'reason-initial';
      case 'regeneration':
        return 'reason-regeneration';
      case 'ldap_update':
        return 'reason-manual';
      case 'template_change':
        return 'reason-rotation';
      case 'override':
        return 'reason-manual';
      default:
        return 'reason-default';
    }
  };

  const getReasonLabel = (reason) => {
    switch (reason?.toLowerCase()) {
      case 'initial':
        return 'Initial';
      case 'regeneration':
        return 'Regeneration';
      case 'ldap_update':
        return 'LDAP Update';
      case 'template_change':
        return 'Template Change';
      case 'override':
        return 'Manual Override';
      default:
        return reason || 'Unknown';
    }
  };

  const formatDate = (dateString) => {
    return formatDisplayDateTime(dateString);
  };

  const formatSystemName = (name) => {
    if (!name) return 'Unknown';
    return name
      .replace(/-/g, ' ')
      .replace(/_/g, ' ')
      .replace(/\b\w/g, l => l.toUpperCase());
  };

  const changedFieldLabels = (entry.metadata?.changedFields || [])
    .map((field) => IMAP_FIELD_LABELS[field])
    .filter(Boolean);

  return (
    <div className={`history-card ${isSelected ? 'selected' : ''}`}>
      <div className="history-card-header">
        <div className="history-card-main">
          <label className="selection-checkbox">
            <input
              type="checkbox"
              checked={isSelected}
              onChange={onSelect}
              disabled={!canSelect && !isSelected}
              aria-label={`Select version ${entry.id} for comparison`}
            />
            <span className="checkbox-custom"></span>
          </label>

          <div className="system-info">
            <h4 className="system-name">{formatSystemName(entry.system)}</h4>
            <span className="version-id">Version {entry.id}</span>
          </div>

          <span className={`reason-badge ${getReasonColor(entry.reason)}`}>
            {getReasonLabel(entry.reason)}
          </span>
        </div>

        <div className="history-card-meta">
          <span className="timestamp">{formatDate(entry.timestamp)}</span>
          <button
            className="btn-toggle-details"
            onClick={() => setShowDetails(!showDetails)}
            aria-expanded={showDetails}
          >
            {showDetails ? 'Hide Details' : 'Show Details'}
            <span className={`toggle-icon ${showDetails ? 'expanded' : ''}`}>▼</span>
          </button>
        </div>
      </div>

      {showDetails && (
        <div className="history-card-details">
          <div className="credential-details">
            <div className="detail-field">
              <label>Username</label>
              <div className="detail-value">
                <code>{entry.username}</code>
              </div>
            </div>

            <div className="detail-field">
              <label>Password</label>
              <CredentialRevealer versionId={entry.id} />
            </div>

            <div className="detail-row">
              <div className="detail-field half">
                <label>Template Version</label>
                <div className="detail-value">
                  <span className="template-badge">
                    {entry.templateVersion === null || entry.templateVersion === undefined ? '—' : `v${entry.templateVersion}`}
                  </span>
                </div>
              </div>

              <div className="detail-field half">
                <label>Generated By</label>
                <div className="detail-value">
                  <span className="user-badge">{entry.createdBy?.name || 'System'}</span>
                </div>
              </div>
            </div>

            {entry.notes && (
              <div className="detail-field">
                <label>Notes</label>
                <div className="detail-value notes">
                  {entry.notes}
                </div>
              </div>
            )}

            {entry.metadata?.mode === 'imap_deterministic' && changedFieldLabels.length > 0 && (
              <div className="detail-field">
                <label>Information Changed</label>
                <div className="detail-value changed-field-list">
                  {changedFieldLabels.map((label) => (
                    <span className="changed-field-chip" key={label}>{label}</span>
                  ))}
                </div>
              </div>
            )}

            {entry.metadata?.mode === 'provider_recorded' && (
              <div className="detail-field">
                <label>Source</label>
                <div className="detail-value">
                  Password recorded by IT from the email provider (not generated in-app).
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export default CredentialHistoryCard;
